---
name: "nightly-6"
on:
    schedule:
        - cron: '42 5 * * *'
    workflow_dispatch:

jobs:
    nightly-7:
        name: "dispatch-nightly-6"
        runs-on: ubuntu-22.04
        permissions: write-all
        steps:
            - name: Checkout '6'
              uses: actions/checkout@v4
              with:
                  ref: '6'

            - name: Execute 'ci.yml' on '6'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh workflow run ci.yml --ref 6
